### ISSUE TITLE
Cannot connect (AttributeError: 'NoneType' object has no attribute 'group')

### ISSUE THREAD

**Issue by fronczek** [datagutten/apc-smartconnect-py#2]
Seems something is wrong:
```
Traceback (most recent call last):
  File "/home/xxx/apc-smartconnect-py/sample.py", line 11, in <module>
    smart.login(sys.argv[1], sys.argv[2])
  File "/home/xxx/apc-smartconnect-py/apc_smartconnect/APCSmartConnect.py", line 85, in login
    frontdoor = self.get_meta_redirect(response2.text)
  File "/home/xxx/apc-smartconnect-py/apc_smartconnect/APCSmartConnect.py", line 50, in get_meta_redirect
    url = matches.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
Any idea why? UPS is visible on APC portal...

**Comment by datagutten** [comment]
Sometimes when you try to logon too many times you get a cookie which seems to trigger a captcha. Removing cookies seems to avoid this. I will add a check for this and throw a clearer exception message.
